# Generated by Django 4.0.6 on 2022-08-04 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_roles_alter_user_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.hospital'),
        ),
    ]
