# Generated by Django 4.0.6 on 2022-07-15 08:54

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=255)),
                ('hospital_address', models.CharField(max_length=100)),
                ('hospital_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('hospital_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_first_name', models.CharField(max_length=100)),
                ('staff_last_name', models.CharField(max_length=100)),
                ('staff_middle_name', models.CharField(max_length=100)),
                ('staff_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=20)),
                ('staff_birthday', models.DateField(default=None)),
                ('staff_profile_pic', models.ImageField(upload_to='')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.hospital')),
            ],
        ),
    ]
