# Generated by Django 4.0.6 on 2022-07-15 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='staff_profile_pic',
            field=models.ImageField(upload_to='profile_pic/'),
        ),
    ]
